### ISSUE TITLE
Provide prebuilt binaries

### ISSUE THREAD

**Issue by jamesford42** [kakaroto/RCOMage#3]
Having at least one 'release' for downloading the prebuilt binaries would be handy... a lot of people (or at least me) have no experience using makefiles for builds, and am not setup to do so on windows.

**Comment by ErikPshat** [comment]
> Having at least one 'release' for downloading the prebuilt binaries would be handy... a lot of people (or at least me) have no experience using makefiles for builds, and am not setup to do so on windows.

http://endlessparadigm.com/forum/showthread.php?tid=19501

**Comment by kakaroto** [comment]
This is not my project or code, so I don't make the releases, I've only offered to host the sources (think of it as a clone of a private repo), which is why there are no binaries provided as release. @ErikPshat provided you with the official release page I suppose.
Either way, it's actually a good idea to have releases for people who don't want to go looking for the binaries, so I've just downloaded the file and re-uploaded it as a release on this repo :
https://github.com/kakaroto/RCOMage/releases/tag/1.1.0

**Comment by ErikPshat** [comment]
> I've just downloaded the file and re-uploaded it as a release on this repo :
> https://github.com/kakaroto/RCOMage/releases/tag/1.1.0

I think you missed the version a little I think you missed the version a little
https://i6.imageban.ru/out/2018/11/21/0603d4763c6dede8c5e47f408770314c.png

**Comment by kakaroto** [comment]
Yeah, I knew I saw 1.1.1  before, but couldn't see it in the attachments of that post, and I actually made the release with the 1.1.0 version binary from the attachment section at the bottom. I've redone the tag and release with the correct binary now, thanks for noticing!
